In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
pollster_df = pd.read_csv(r'C:\Users\Lyons\OneDrive\Desktop\IML-FALL2025---Voter-Bias\webscraped_data\pollsters_2014_2024.csv')
alabama_cutoff_df = pd.read_csv(r'C:\Users\Lyons\OneDrive\Desktop\IML-FALL2025---Voter-Bias\voter_cutoff\weighted\voter_team_cutoff50_weighted_alabama.csv')

In [16]:
pollster_df = pollster_df.rename(columns = {'pollster_name' : 'voter'})
pollster_df['voter'] = pollster_df['voter'].str.lower()
pollster_df['voter'] = pollster_df['voter'].str.replace(' ', '-')
pollster_df

               voter                affiliation          city state  year
0          adam-jude          The Seattle Times       Seattle    WA  2014
1        adam-sparks         Daily News Journal  Murfreesboro    TN  2014
2        adam-zucker         CBS Sports Network        Summit    NJ  2014
3    bill-rabinowitz      The Columbus Dispatch      Columbus    OH  2014
4       bob-asmussen     Champaign News-Gazette     Champaign    IL  2014
..               ...                        ...           ...   ...   ...
704    steve-wiseman             The Herald-Sun        Durham    NC  2024
705   steven-johnson   Fort Worth Star-Telegram     Arlington    TX  2024
706       tom-murphy  Arkansas Democrat-Gazette   Little Rock    AR  2024
707      trevor-hass                 Boston.com        Boston    MA  2024
708       zach-klein                        WSB       Atlanta    GA  2024

[709 rows x 5 columns]

In [26]:
df = alabama_cutoff_df.merge(pollster_df[['voter', 'city', 'state', 'year']], on = 'voter', how = 'left')
df.year = df.year.astype('str').str.replace('.0', '')
df

,voter,team,bias1,bias2,bias3,bias0_ap,bias0_mean,n,city,state,year
0,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2018
1,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2019
2,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2020
3,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2021
4,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2022
...,...,...,...,...,...,...,...,...,...,...,...
403,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2018
404,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2019
405,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2020
406,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2021
407,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2024

In [32]:
team = 'alabama' # <- starting with alabama to test, add more from current map if we want to test more

team_state_map = {
    'alabama' : 'AL', 
    'michigan' : 'MI', 
    'ohio-state' : 'OH', 
    'lsu' : 'LA', 
    'oklahoma' : 'OK'
}

team_state = team_state_map[team]
df['in_state'] = df.state.eq(team_state)
df

,voter,team,bias1,bias2,bias3,bias0_ap,bias0_mean,n,city,state,year,in_state
0,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2018,False
1,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2019,False
2,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2020,False
3,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2021,False
4,don-williams,alabama-crimson-tide,-0.149830,-1.458478,-1.426110,-0.387755,-2.505449,98,Lubbock,TX,2022,False
...,...,...,...,...,...,...,...,...,...,...,...,...
403,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2018,False
404,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2019,False
405,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2020,False
406,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2021,False
407,dylan-sinn,alabama-crimson-tide,0.294797,-1.060159,-1.024766,0.774648,-1.408592,71,Fort Wayne,IN,2024,False